adoption:
    resource: "@AdoptionBundle/Resources/config/routing.yml"
    prefix:   /adoption

shop:
    resource: "@ShopBundle/Resources/config/routing.yml"
    prefix:   /shop

base:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"