<?php

namespace BaseBundle\Repository;

/**
 * wishlistAdoptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class wishlistAdoptionRepository extends \Doctrine\ORM\EntityRepository
{
}
